// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD74opGpGV0HN3DUsWbbtEXavBzFAGuu3E',
    appId: '1:71512324137:web:4ebd183bca5dbea25bc438',
    messagingSenderId: '71512324137',
    projectId: 'my-app-flutter-project',
    authDomain: 'my-app-flutter-project.firebaseapp.com',
    storageBucket: 'my-app-flutter-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQwwRmeWnAeD7ua-Mw2zW-nnrRVywhKVE',
    appId: '1:71512324137:android:9f2e48df05108ece5bc438',
    messagingSenderId: '71512324137',
    projectId: 'my-app-flutter-project',
    storageBucket: 'my-app-flutter-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD72XRAHlV9O14yDOrJyf_DLAn6YNaRVho',
    appId: '1:71512324137:ios:6a46c3ac7c1a3d705bc438',
    messagingSenderId: '71512324137',
    projectId: 'my-app-flutter-project',
    storageBucket: 'my-app-flutter-project.appspot.com',
    iosClientId: '71512324137-oq1ic25jq97n2p1ipbmr0t3a4lfdg7fp.apps.googleusercontent.com',
    iosBundleId: 'com.therat.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD72XRAHlV9O14yDOrJyf_DLAn6YNaRVho',
    appId: '1:71512324137:ios:014cdd1e48ce077a5bc438',
    messagingSenderId: '71512324137',
    projectId: 'my-app-flutter-project',
    storageBucket: 'my-app-flutter-project.appspot.com',
    iosClientId: '71512324137-fvihtou04shk5db4hupl36r641q1dkil.apps.googleusercontent.com',
    iosBundleId: 'com.therat.myap',
  );
}
