// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHRSploz6PNgFehvQ8fTQelCM2Lxv3GB0',
    appId: '1:701114978322:web:0995c7c800110af2bd48cb',
    messagingSenderId: '701114978322',
    projectId: 'note-app-myapp',
    authDomain: 'note-app-myapp.firebaseapp.com',
    storageBucket: 'note-app-myapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD30Bsrve0rxrQU83krRxhEhcrf8S5fDNg',
    appId: '1:701114978322:android:d5de1877f9a83835bd48cb',
    messagingSenderId: '701114978322',
    projectId: 'note-app-myapp',
    storageBucket: 'note-app-myapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAxQWYrxLotKtxARNra6_xvX2EXJQR-sk',
    appId: '1:701114978322:ios:6a81e0a2d83e3e32bd48cb',
    messagingSenderId: '701114978322',
    projectId: 'note-app-myapp',
    storageBucket: 'note-app-myapp.appspot.com',
    iosClientId: '701114978322-qg7e4ku7ttf48vu3et83ikdqiihuodbu.apps.googleusercontent.com',
    iosBundleId: 'com.ther',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAxQWYrxLotKtxARNra6_xvX2EXJQR-sk',
    appId: '1:701114978322:ios:58af18a2eb0a243ebd48cb',
    messagingSenderId: '701114978322',
    projectId: 'note-app-myapp',
    storageBucket: 'note-app-myapp.appspot.com',
    iosClientId: '701114978322-ctot9lebs67s8ccomha7l0edn0rm1d35.apps.googleusercontent.com',
    iosBundleId: 'com.th',
  );
}
